spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///Users//hoijoo//Documents//config"
        git:
          uri: "https://github.com/hoijookim/msa-banking-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true # override local changes whenever trying to start or restart always
server:
  port: 8071
